name: secret_handler.yml

on:
  push:
    branches:  [main]
  pull_request:
    branches:  [main]

jobs:
  Importing_credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: run_test
        env:
            TESTNET_SERVICE_ACCOUNT_JSON: ${{secrets.TESTNET_SERVICE_ACCOUNT_JSON}}
             
