name: main.yml

on:
  push:
    branches:  [main]
  pull_request:
    branches:  [main]

jobs:
  Importing_credentials:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: run_test
      run: echo "$TESTNET_SERVICE_ACCOUNT_JSON"
      env:
          TESTNET_SERVICE_ACCOUNT_JSON: ${{secrets.TESTNET_SERVICE_ACCOUNT_JSON}}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: |
           cd /.buildkite/hooks/
           bash post-command

      
      env:
        TESTNET_SERVICE_ACCOUNT_JSON: ${{ secrets.TESTNET_SERVICE_ACCOUNT_JSON }}
